---
- name: Setup Vprofile Bastion host
  hosts: localhost
  connection: local 
  gather_facts: True
  become: yes
  become_user: root

  tasks:
    - name: Import VPC setup variables
      include_vars: vars/vpc-output_vars

    - name: Import Bastion setup variables
      include_vars: vars/my_vpc_setup.yml

    - name: Create Bastion host Keypair
      ec2_key:
        name: bastion-key 
        region: "{{region}}"
      register: key_out

    - name: Save Private key into file bastion-key.pem
      copy:
        content: "{{key_out.key.private_key}}"
        dest: "./bastion-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Bastion Host Security Group
      ec2_group: 
        name: Bastion-host-sg
        description: Allow port 22 from my ip address  
        region: "{{region}}"
        vpc_id: "{{vpcid}}"  
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{my_ip}}"
      register: BastionSG_out
    
    - name: Create Bastion host
      ec2_instance:
        key_name: bastion-key 
        region: "{{region}}"
        instance_type: t2.micro
        image_id: "{{my_bastion_ami}}"
        wait: true
        wait_timeout: 300
        tags:
           Name: "Bastion Host"
           Project: Vprofile 
           Owner: "Devops Team"
        # count: 1
        # count_tag: 
        #   Name: "Bastion Host"
        #   Project: Vprofile
        #   Owner: Devops Team
        security_group : "{{BastionSG_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastHostout 
    - debug:
        name: Get Instance Metadata
        vars: bastHostout

    - name: Update and Install ansible 
      apt: 
        name: ansible
        state: present 
        update_cache: true
      delegate_to: "{{bastHostout.instances[0].network_interfaces[0].public_ip_address }}"
      when: bastHostout.instances[0].network_interfaces[0].public_ip_address 

    - name: Install git 
      apt:
        name: git
        state: present 
      delegate_to: "{{bastHostout.instances[0].network_interfaces[0].public_ip_address}}"
      when: bastHostout.instances[0].network_interfaces[0].public_ip_address 
  
    - name: Clone Vprofile lastest repository
      command: 
        cmd: git clone https://github.com/robudexIT/vprofile-project.git
      delegate_to: "{{bastHostout.instances[0].network_interfaces[0].public_ip_address}}"
      when: bastHostout.instances[0].network_interfaces[0].public_ip_address  
        
         
    - name: Insert/Update "BastionSGid" in vars/vpc-output_vars  
      blockinfile:
        path: vars/vpc-output_vars
        backup: yes
        block: |
          BastionSGid: {{BastionSG_out.group_id}}
          
          