---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local 
  gather_facts: False 
  tasks: 
    - name: Import VPC setup variables 
      include_vars: vars/vpc-output_vars

    - name: Import vprofile setup Variables
      include_vars: vars/my_vprofile_ec2_setup.yml


    - name: Create vporfile ec2 key
      ec2_key:
        name: vprofilekey
        region: "{{region}}"
      register: vprofilekey_out

    - name: Save private key into file loginkey_vpro.pem 
      copy: 
        content: "{{vprofilekey_out.key.private_key}}"
        dest: "./vprofilekey.pem" 
        mode: 0600
      when: vprofilekey_out.changed

    - name: Create Security Group for Load Balancer
      ec2_group:
        name: elb-sg 
        description: This security_group is used by Load Balancer
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        rules: 
          - proto: tcp
            from_port: 80
            to_port: 80 
            cidr_block: 0.0.0.0/0
          - proto: 443
            from_port: 443 
            to_port: 443
            cidr_block: 0.0.0.0/0
      register: elbSG_out     


    - name: Create Security Group for Vprofile Stack
      ec2_group: 
        name: vprofileSG
        description: Security Group for Vprofile Stack
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        state: present
        rules: 
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{elbSG_out.group_id}}"
          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{BastionSGid}}" 
      register: vprofileSG_out
        

    - name: Update Security Group with its own sg id 
      ec2_group:
        name:  vprofileSG
        description: Security Group for Vprofile Stack
        region: "{{region}}"
        vpc_id: "{{vpcid}}"
        purge_rules: no
        rules:
         - proto: all 
           group_id: "{{vprofileSG_out.group_id}}"

         
    - name: Create Nginx web01
      ec2_instance:
        name: web01
        instance_type: "t2.micro"
        region: "{{region}}"
        vpc_subnet_id: "{{privsub1id}}"
        image_id: "{{nginx_ami}}"
        key_name: vprofilekey
        security_group: vprofileSG
        tags: 
          Name: "web01"
          Project: Vprofile
          Owner: Devops Team
      register: web01_out
  

    - name: Debug Instance private ip address
      debug:
       var: web01_out.instances[0].network_interfaces[0].private_ip_address
        
      
    - name: Create tomcat app01
      ec2_instance:
        name: app01
        instance_type: "t2.micro"
        image_id: "{{tomcat_ami}}"
        key_name: vprofilekey
        security_group: vprofileSG
        vpc_subnet_id: "{{privsub1id}}"
        tags: 
          Name: "app01"
          Project: Vprofile
          Owner: Devops Team
        region: "{{region}}"
      register: app01_out
        
    - name: Create memcache mc01
      ec2_instance:
        name: "mc01"
        instance_type: "t2.micro"
        key_name: vprofilekey
        image_id: "{{memcache_ami}}"
        vpc_subnet_id: "{{privsub1id}}"
        security_group: vprofileSG
        tags: 
          Name: "mc01"
          Project: Vprofile
          Owner: Devops Team
        region: "{{region}}"
      register: mc01_out

    - name: Create RabbitMQ rmq01
      ec2_instance:
        name: "rmq01"
        key_name: vprofilekey
        image_id: "{{rmq_ami}}"
        instance_type: "t2.micro"
        vpc_subnet_id: "{{privsub1id}}"
        security_group: vprofileSG
        tags:
          Name: "rmq01"
          Project: Vprofile 
          Owner: Devops Team
        region: "{{region}}"
      register: rmq01_out  
       
    - name: Create Mysql db01
      ec2_instance:
        name: "db01"
        key_name: vprofilekey 
        instance_type: "t2.micro" 
        image_id: "{{mysql_ami}}"
        vpc_subnet_id: "{{privsub1id}}"
        security_group: vprofileSG
        tags: 
          Name: "db01" 
          Project: Vprofile 
          Owner: Devops Team 
        region: "{{region}}"
      register: db01_out
    
    - name: Debug Instance private ip address
      debug:
       var: db01_out.instances[0].network_interfaces[0].private_ip_address
      #  createing elb
    - local_action:
        module: ec2_elb_lb
        region: "{{region}}"
        state: present
        name: vprofileELB
        instance_ids:
         - "{{web01_out.instance_ids[0]}}"
        purge_instance_ids: true 
        security_group_ids: 
         - "{{elbSG_out.group_id}}"
        subnets: 
          - "{{ pubsub1id }}"
          - "{{ pubsub2id }}"
          - "{{ pubsub3id }}"
        listeners:
          - protocol: http
            load_balancer_port: 80 
            instance_port: 80
        
    - name: Insert/Update Hosts IP and Name in file provision-stack/group_vars/hostsip
      blockinfile: 
        path: provision-stack/group_vars/hostsip
        block: |
          web01_ip: {{web01_out.instances[0].network_interfaces[0].private_ip_address }}
          app01_ip: {{app01_out.instances[0].network_interfaces[0].private_ip_address}}
          rmq01_ip: {{rmq01_out.instances[0].network_interfaces[0].private_ip_address}}
          db01_ip:  {{db01_out.instances[0].network_interfaces[0].private_ip_address}}
          mc01_ip:  {{mc01_out.instances[0].network_interfaces[0].private_ip_address}}

    - name: Copy login key to provision stack directory
      copy: 
        src: loginkey_vpro.pem
        dest: provision-stack/loginkey_vpro.pem
        mode: 0400
    

    - name: Insert/Update Inventory file provision-stack/inventory-vpro
      blockinfile:
        path: provision-stack/inventory-vpro
        block: |
          web01 ansible_host={{web01_out.instances[0].network_interfaces[0].private_ip_address }}
          app01 ansible_host={{app01_out.instances[0].network_interfaces[0].private_ip_address}}
          rmq01 ansible_host={{rmq01_out.instances[0].network_interfaces[0].private_ip_address}}
          db01  ansible_host={{db01_out.instances[0].network_interfaces[0].private_ip_address}}
          mc01  ansible_host={{mc01_out.instances[0].network_interfaces[0].private_ip_address}}
          cntl  ansible_host=127.0.0.1 ansible_connection=local 
          
          [websrvgrp]
          web01

          [appsrvgrp]
          app01

          [rmqsrvgrp]
          rmq01

          [mcsrvgrp]
          mc01

          [dbsrvgrp]
          db01

          [control]
          cntl

          [stack_inst:children]
          websrvgrp
          appsrvgrp
          rmqsrvgrp
          mcsrvgrp
          dbsrvgrp

          [stack_inst:vars]
          ansible_user=ubuntu
          ansible_ssh_private_key_file=loginkey_vpro.pem
          #ansible_python_interpreter=/usr/bin/python3