--- 
- name: Install and Setup RabbitMQ with user 
  hosts: rmqsrvgrp
  gather_facts: no 
  tasks: 
    
    # - name: Install Erlang Repository package 
    #   apt:
    #      deb: https://packages.erlang-solutions.com/erlang-solutions_1.0_all.deb
    #   tags: 
    #     - package 
    
    # - name: Add an Erlang Solution public Key 
    #   apt_key: 
    #     url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
    #     state: present 
    #   tags: 
    #     - package 
    - name: Install dependies 
      apt: 
        name: "{{item}}"
        state: present 
        update_cache: yes
      loop: 
       - ca-certificates
       - curl
       - gnupg 
       - apt-transport-https
       
    - name: Copy mq.sh to /root of the remote hosts 
      become: yes
      copy: 
        src: templates/mq.sh
        dest: /root/mq.sh 
        owner: root 
        group: root
        mode: 777
        remote_src: no

    - name:  Execute mq.sh
      become: yes
      shell: /root/mq.sh


    - name: Copy rabbitmq.list to /etc/apt/sources.list.d of the rmqsrvgrp hosts 
      become: yes
      copy: 
        src: templates/rabbitmq.list
        dest: /etc/apt/sources.list.d/rabbitmq.list 
        owner: root 
        group: root
        remote_src: no

    - name: Install erlang 
      apt: 
        name: "{{item}}"
        state: present 
        update_cache: yes 
        cache_valid_time: 86400 
      loop: 
       - erlang-base
       - erlang-asn1
       - erlang-crypto
       - erlang-eldap
       - erlang-ftp
       - erlang-inets
       - erlang-mnesia
       - erlang-os-mon
       - erlang-parsetools
       - erlang-public-key
       - erlang-runtime-tools
       - erlang-snmp
       - erlang-ssl
       - erlang-syntax-tools
       - erlang-tftp
       - erlang-tools
       - erlang-xmerl
      tags: 
       - package 

    # - name: Install erlang 
    #   apt: 
    #     name: erlang 
    #     state: present 
    #     update_cache: yes 
    #     cache_valid_time: 86400 
    #   tags: 
    #     - package 


    # - name: Add an Apt signing key, uses whichever key is at the URL
    #   apt_key:
    #     url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    #     state: present
    #   tags:
    #     - package

    # - apt_repository:
    #     repo: deb https://dl.bintray.com/rabbitmq/debian bionic main
    #     state: present
    #   tags:
    #     - package        
  
    - name: Install Rabbit MQ 
      apt: 
        name: rabbitmq-server 
        state: present 
        update_cache: yes 
        # dpkg_options: 'fix-missing'
      tags: 
        - package 
    
    - name: Start and Enable RMQ 
      service: 
        name: rabbitmq-server 
        state: started
        enabled: yes 
      tags: 
        - svc 

    - name: Config Setup 
      copy: 
        content: | 
          [{rabbit, [{loopback_users, []}]}].
        dest: /etc/rabbitmq/rabbitmq.config 
      notify:
        - Restart RMQ
      tags: 
        - conf

    - rabbitmq_user:
        user: test
        password: test
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        tags: administrator
        state: present
      notify:
        - Restart RMQ
      tags:
        - conf

    - name: Enables the rabbitmq_management plugin
      rabbitmq_plugin:
        names: rabbitmq_management
        state: enabled
      notify:
        - Restart RMQ
      tags:
        - package

 
  handlers:
    - name: Restart RMQ 
      service: 
        name: rabbitmq-server 
        state: restarted 




  
    
    